const $=id=>document.getElementById(id);const FALLBACK={lat:51.4988,lon:3.6136,name:'Middelburg (fallback)'};let state={loc:null,weather:null,iss:[],aurora:null,moon:null};
const fmt=t=>new Intl.DateTimeFormat('nl-NL',{hour:'2-digit',minute:'2-digit'}).format(t);const deg=r=>r*180/Math.PI;const dir=d=>['N','NO','O','ZO','Z','ZW','W','NW'][Math.round(((d%360)+360)%360/45)%8];
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`${r.status}`);return r.json()}
function getLocation(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve(FALLBACK);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,name:'Jouw locatie'}),()=>resolve(FALLBACK),{enableHighAccuracy:true,timeout:7000,maximumAge:300000})})}
async function loadWeather(l){const vars='cloud_cover,precipitation_probability,visibility,temperature_2m,is_day';const u=`https://api.open-meteo.com/v1/forecast?latitude=${l.lat}&longitude=${l.lon}&current=temperature_2m,is_day,cloud_cover&hourly=${vars}&forecast_days=2&timezone=auto`;return json(u)}
function weatherAt(w,date){const ts=date.getTime();let best=0,diff=Infinity;w.hourly.time.forEach((x,i)=>{const d=Math.abs(new Date(x).getTime()-ts);if(d<diff){diff=d;best=i}});return{cloud:w.hourly.cloud_cover[best],rain:w.hourly.precipitation_probability[best],vis:w.hourly.visibility[best],temp:w.hourly.temperature_2m[best],day:w.hourly.is_day[best]}}
function sunAltitude(l,date){const o=new Astronomy.Observer(l.lat,l.lon,0);return Astronomy.Horizon(date,o,Astronomy.Equator(Astronomy.Body.Sun,date,o,true,true).ra,Astronomy.Equator(Astronomy.Body.Sun,date,o,true,true).dec,'normal').altitude}
function loadMoon(l){const now=new Date(),o=new Astronomy.Observer(l.lat,l.lon,0),eq=Astronomy.Equator(Astronomy.Body.Moon,now,o,true,true),h=Astronomy.Horizon(now,o,eq.ra,eq.dec,'normal'),phase=Astronomy.Illumination(Astronomy.Body.Moon,now);return{alt:h.altitude,az:h.azimuth,illum:phase.phase_fraction*100}}
async function loadTLE(){const text=await fetch('https://celestrak.org/NORAD/elements/gp.php?CATNR=25544&FORMAT=TLE',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.text()});const a=text.trim().split(/\r?\n/);return[a[a.length-2],a[a.length-1]]}
function satLook(satrec,l,date){const pv=satellite.propagate(satrec,date);if(!pv.position)return null;const gmst=satellite.gstime(date),gd={longitude:l.lon*Math.PI/180,latitude:l.lat*Math.PI/180,height:0},ecf=satellite.eciToEcf(pv.position,gmst),look=satellite.ecfToLookAngles(gd,ecf);return{alt:deg(look.elevation),az:(deg(look.azimuth)+360)%360,pos:pv.position}}
function sunlit(pos,date){const sunAu=Astronomy.GeoVector(Astronomy.Body.Sun,date,true);const AU=149597870.7,s=[sunAu.x*AU,sunAu.y*AU,sunAu.z*AU],sm=Math.hypot(...s),u=s.map(x=>x/sm),dot=pos.x*u[0]+pos.y*u[1]+pos.z*u[2];if(dot>=0)return true;const px=pos.x-dot*u[0],py=pos.y-dot*u[1],pz=pos.z-dot*u[2];return Math.hypot(px,py,pz)>6378.137}
async function loadISS(l){const [a,b]=await loadTLE(),satrec=satellite.twoline2satrec(a,b),start=Date.now(),end=start+24*3600e3,step=20e3,passes=[];let active=null;for(let t=start;t<=end;t+=step){const date=new Date(t),look=satLook(satrec,l,date);if(!look)continue;const ok=look.alt>=10;if(ok&&!active)active={start:date,maxAlt:look.alt,maxAz:look.az,visible:false};if(ok&&active){if(look.alt>active.maxAlt){active.maxAlt=look.alt;active.maxAz=look.az}const dark=sunAltitude(l,date)<-6;if(dark&&sunlit(look.pos,date))active.visible=true}if(!ok&&active){active.end=date;if(active.visible)passes.push(active);active=null}}return passes}
async function loadAurora(l){try{const d=await json('https://services.swpc.noaa.gov/json/ovation_aurora_latest.json'),coords=d.coordinates||[];let best=0;for(const p of coords){const lon=p[0]>180?p[0]-360:p[0],lat=p[1],v=p[2],dist=Math.hypot((lat-l.lat)*1.2,(lon-l.lon)*Math.cos(l.lat*Math.PI/180));if(dist<4&&v>best)best=v}return{value:best,time:d['Forecast Time']||d['Observation Time']||null}}catch{return null}}
function render(){const l=state.loc,w=state.weather,now=new Date();$('location').textContent=l.name;const wa=weatherAt(w,now),sa=sunAltitude(l,now);$('darkness').textContent=sa<-18?'Astronomisch donker':sa<-6?'Schemering':sa<0?'Lichte schemering':'Daglicht';$('weather').textContent=`${Math.round(wa.cloud)}% bewolking · ${Math.round(wa.temp)}°C`;const m=state.moon;$('moon').textContent=`${Math.round(m.illum)}% verlicht`;$('moonSub').textContent=m.alt>0?`${Math.round(m.alt)}° hoog richting ${dir(m.az)}`:'Onder de horizon';if(state.iss.length){const p=state.iss[0];$('iss').textContent=`${fmt(p.start)} · max ${Math.round(p.maxAlt)}°`;$('issSub').textContent=`Richting ${dir(p.maxAz)} · zonverlicht én donkere/schemerige hemel tijdens passage.`;$('iss').className='good'}else{$('iss').textContent='Geen goede zichtbare passage';$('issSub').textContent='Geen passage ≥10° gevonden die tegelijk zonverlicht is bij voldoende donkere hemel.'}if(state.aurora){const a=state.aurora.value;$('aurora').textContent=a>=20?'Verhoogd signaal':a>=8?'Zwak signaal':'Geen lokaal signaal';$('auroraSub').textContent=`OVATION nabij jouw locatie: ${Math.round(a)}%. Indicatief, geen zichtbaarheidsgarantie.`}else{$('aurora').textContent='Auroradata niet beschikbaar'}const cloud=wa.cloud,rain=wa.rain,iss=state.iss[0];let verdict='Geen sterke reden om nu naar buiten te gaan',reason='Ik zie nu geen combinatie van een bijzonder event en goede omstandigheden.',cls='';if(iss&&iss.start-now<45*60000&&cloud<55&&rain<35){verdict='Ja — houd de ISS in de gaten';reason=`Een praktisch zichtbare ISS-passage begint rond ${fmt(iss.start)}. Bewolking is ongeveer ${Math.round(cloud)}%.`;cls='good'}else if(state.aurora&&state.aurora.value>=20&&sa<-6&&cloud<45){verdict='Kijk even naar buiten';reason='NOAA toont een verhoogd aurorasignaal nabij je locatie en de hemel is voldoende donker.';cls='warn'}$('verdict').textContent=verdict;$('verdict').className=cls;$('reason').textContent=reason;$('updated').textContent=`Bijgewerkt ${fmt(now)} · bronfouten worden niet als positief advies geïnterpreteerd.`;const rows=[];for(let h=0;h<6;h++){const d=new Date(now.getTime()+h*3600e3),x=weatherAt(w,d);rows.push(`<div class="timeline-row"><span>${fmt(d)}</span><span>${Math.round(x.cloud)}% ☁︎ · ${Math.round(x.rain)}% regen</span></div>`)}$('timeline').innerHTML=rows.join('')}
async function refresh(){try{$('verdict').textContent='Hemel wordt gecontroleerd';state.loc=await getLocation();const [w,iss,a]=await Promise.all([loadWeather(state.loc),loadISS(state.loc).catch(()=>[]),loadAurora(state.loc)]);state.weather=w;state.iss=iss;state.aurora=a;state.moon=loadMoon(state.loc);render()}catch(e){$('verdict').textContent='Live controle niet volledig gelukt';$('reason').textContent='Vernieuw de pagina. Zonder actuele brondata geeft Night Sky Thomas geen positief kijkadvies.';console.error(e)}}
$('locate').addEventListener('click',refresh);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});refresh();